# Generated by Django 4.0.4 on 2022-05-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descriptions',
            new_name='description',
        ),
    ]
